### ISSUE TITLE
Vytvorenie USE case diagramu

### ISSUE THREAD

**Issue by cheetahzlesa** [TIS2024-FMFI/preteky#34]

**Comment by MiriamGrznarova** [comment]
![use_case_diagram](https://github.com/user-attachments/assets/64961fd1-5616-419d-ad83-8db26397ea10)
Spravila som use case diagram, prosím pozrite sa na to, či tam niečo nechýba. Ďakujem :).

**Comment by MiriamGrznarova** [comment]
![Image](https://github.com/user-attachments/assets/39dc3bda-002e-493a-a365-364ad77cec50)
upravila som to znova, môžete skontrľovať, či je to ok?
